example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_xml, show_json, show_xml_by_id, show_json_by_id
from wishlist.views import register, login_user, logout_user
from wishlist.views import show_wishlist_ajax, add_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', add_wishlist_ajax, name='add_wishlist_ajax')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from wishlist.models import BarangWishlist

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Elsa Giana Abigail Sitompul',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    context = {
    'nama': 'Elsa Giana Abigail Sitompul',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def add_wishlist_ajax(request: HttpRequest):
    if request.method == "POST":
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        new_barang =  BarangWishlist(
            nama_barang = nama_barang,
            harga_barang = harga_barang,
            deskripsi = deskripsi
        )
        new_barang.save()
        return HttpResponse(serializers.serialize("json", [new_barang]), content_type='application/json')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-primary bg-opacity-50">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Wishlist</a>
          </li>
        </ul>
        <span class="navbar-brand mb-0 h1">Elsa Giana Abigail Sitompul</span>
        <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
      </div>
    </div>
  </nav>

 
<div class="bg-primary p-2 bg-opacity-10">
  <div class="container text-center">   
<table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">Nama Barang</th>
        <th scope="col">Harga Barang</th>
        <th scope="col">Deskripsi</th>
      </tr>
    </thead>
    {% for barang in list_barang %}
    <tbody>
      <tr>
        <td>{{barang.nama_barang}}</td>
        <td>{{barang.harga_barang}}</td>
        <td>{{barang.deskripsi}}</td>
      </tr>
    </tbody>
    {% endfor %}    
  </table>
</div>

<h5>Sesi terakhir login: {{ last_login }}</h5>



</div>
{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-primary bg-opacity-50">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'wishlist:show_wishlist' %}">Wishlist</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'wishlist:show_wishlist_ajax' %}">Wishlist Ajax</a>
          </li>
        </ul>
        <span class="navbar-brand mb-0 h1">{{ nama }}</span>
        <a class="btn btn-danger" href="{% url 'wishlist:logout' %}">Logout</a>
      </div>
    </div>
  </nav>

 
<div class="bg-primary p-2 bg-opacity-10">
    <div class="container text-center">   
        <table class="table table-striped table-dark">
            <thead>
            <tr>
                <th scope="col">Nama Barang</th>
                <th scope="col">Harga Barang</th>
                <th scope="col">Deskripsi</th>
            </tr>
            </thead>
            <tbody id="table-data"></tbody>
        </table>
      
        <h4>Add New Wishlist</h4>
        <form method="POST" action="">
          {% csrf_token %}
          <div class="form-group row mb-2">
            <label for="nama_barang" class="col-sm-2 col-form-label">Nama Barang</label>
            <div class="col-sm-10">
              <input type="text" name="nama_barang" class="form-control" id="nama_barang" placeholder="Nama Barang" class="form-control"/>
            </div>  
          </div>
          <div class="form-group row mb-2">
            <label for="harga_barang" class="col-sm-2 col-form-label">Harga Barang</label>
            <div class="col-sm-10">
              <input type="text" name="harga_barang" class="form-control" id="harga_barang" placeholder="Harga Barang" class="form-control"/>
            </div>  
          </div>
          <div class="form-group row mb-2">
            <label for="deskripsi" class="col-sm-2 col-form-label">Deskripsi</label>
            <div class="col-sm-10">
              <input type="text" name="deskripsi" class="form-control" id="deskripsi" placeholder="Deskripsi" class="form-control"/>
            </div>  
          </div>
            <input class="btn btn-primary" type="submit" value="Submit" id="btn">  
        </form>
    
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script>
          function postNew(e) {
            e.preventDefault()
            const namaBarang = $("#nama_barang").val()
            const hargaBarang = $("#harga_barang").val()
            const deskripsi = $("#deskripsi").val()
        
            const data = {
              nama_barang: namaBarang,
              harga_barang: hargaBarang,
              deskripsi,
              csrfmiddlewaretoken: "{{ csrf_token }}"
            }
        
            $.ajax({
              type: 'POST',
              url: '{% url "wishlist:add_wishlist_ajax" %}',
              data: data, 
              success: () => {
                alert("Success Adding New Wishlist!")
                fetchData()
              },
              dataType: 'json'
            });
          }
        
          function createTable(data) {
            const table = $("#table-data")
            table.empty()
            for (let i = 0; i < data.length; i++) {
              table.append(`
                <tr>
                  <td>${data[i].fields.nama_barang}</td>
                  <td>${data[i].fields.harga_barang}</td>
                  <td>${data[i].fields.deskripsi}</td>
                </tr>
                `)
            }
          }
        
          function fetchData() {
            $.get("/wishlist/json", createTable)
          }
        
          $(document).ready(() => {
            $("#btn").click(postNew)
            fetchData()
          })
        </script>
    </div>


    <h5>Sesi terakhir login: {{ last_login }}</h5>

</div>
{% endblock content %}